"""Build a single-file Unhog.exe with PyInstaller.

Usage (from the repo root, with any Python 3.9+ that is not the Microsoft
Store build):

    python -m venv .venv-build
    .venv-build/Scripts/pip install -r requirements.txt pyinstaller
    .venv-build/Scripts/python build_exe.py

The result is dist/Unhog.exe. It is windowed (no console) and self-contained;
the UI font is read from C:/Windows/Fonts at run time, so nothing else ships.

The version shown in the window title comes from the git tag: the script runs
``git describe`` (or takes the UNHOG_VERSION environment variable if set) and
writes it to unhog/_version.py, which is packaged into the exe.
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VERSION_FILE = os.path.join(HERE, "unhog", "_version.py")


def version_from_git() -> str:
    out = subprocess.run(["git", "describe", "--tags", "--always", "--dirty"], cwd=HERE,
                         capture_output=True, text=True, check=True).stdout.strip()
    return out


version = os.environ.get("UNHOG_VERSION") or version_from_git()
version = version[1:] if version.startswith("v") else version
with open(VERSION_FILE, "w", encoding="utf-8") as f:
    f.write("# Generated by build_exe.py from the git tag; not tracked in git.\n")
    f.write(f'version = "{version}"\n')
print(f"Building Unhog {version}")

cmd = [
    sys.executable, "-m", "PyInstaller",
    "--noconfirm",
    "--clean",
    "--onefile",
    "--noconsole",
    "--name", "Unhog",
    "--paths", HERE,
    "--collect-binaries", "dearpygui",
    "--hidden-import", "unhog._version",
    "--exclude-module", "tkinter",
    "--exclude-module", "unittest",
    "--exclude-module", "test",
    "--distpath", os.path.join(HERE, "dist"),
    "--workpath", os.path.join(HERE, "build"),
    "--specpath", os.path.join(HERE, "build"),
    os.path.join(HERE, "Unhog.pyw"),
]
print(" ".join(cmd))
sys.exit(subprocess.call(cmd, cwd=HERE))
