"""Build the Unhog release files with PyInstaller.

Usage (from the repo root, with any Python 3.9+ that is not the Microsoft
Store build):

    python -m venv .venv-build
    .venv-build/Scripts/pip install -r requirements.txt pyinstaller
    .venv-build/Scripts/python build_exe.py

Two builds are produced in dist/:

- dist/Unhog-win64.zip: a folder with a small Unhog.exe and its runtime in
  _internal/ (PyInstaller one-folder mode). The recommended download: it runs
  in place, so Windows Defender's heuristics have much less to object to.
- dist/Unhog.exe: everything in a single file (one-folder mode's contents
  packed into one exe that unpacks itself to a temp folder on start).

Both are windowed (no console) and self-contained; the UI font is read from
C:/Windows/Fonts at run time, so nothing else ships.

The version shown in the window title comes from the git tag: the script runs
``git describe`` (or takes the UNHOG_VERSION environment variable if set) and
writes it to unhog/_version.py, which is packaged into the builds.
"""

import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(HERE, "dist")
VERSION_FILE = os.path.join(HERE, "unhog", "_version.py")
ZIP_NAME = "Unhog-win64"  # fixed name so the README's latest-release link keeps working


def version_from_git() -> str:
    return subprocess.run(["git", "describe", "--tags", "--always", "--dirty"], cwd=HERE,
                          capture_output=True, text=True, check=True).stdout.strip()


def write_version_file() -> str:
    version = os.environ.get("UNHOG_VERSION") or version_from_git()
    version = version[1:] if version.startswith("v") else version
    with open(VERSION_FILE, "w", encoding="utf-8") as f:
        f.write("# Generated by build_exe.py from the git tag; not tracked in git.\n")
        f.write(f'version = "{version}"\n')
    return version


def pyinstaller(mode: str) -> None:
    """Run PyInstaller in ``--onefile`` or ``--onedir`` mode; output lands in dist/."""
    work = os.path.join(HERE, "build", mode)
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        f"--{mode}",
        "--noconsole",
        "--name", "Unhog",
        "--paths", HERE,
        "--collect-binaries", "dearpygui",
        "--hidden-import", "unhog._version",
        "--exclude-module", "tkinter",
        "--exclude-module", "unittest",
        "--exclude-module", "test",
        "--distpath", DIST,
        "--workpath", work,
        "--specpath", work,
        os.path.join(HERE, "Unhog.pyw"),
    ]
    print(" ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=HERE, check=True)


def main() -> int:
    version = write_version_file()
    print(f"Building Unhog {version}", flush=True)
    shutil.rmtree(DIST, ignore_errors=True)

    # One-folder build -> dist/Unhog/ -> dist/Unhog-win64.zip (folder named Unhog inside).
    pyinstaller("onedir")
    zip_path = shutil.make_archive(os.path.join(DIST, ZIP_NAME), "zip", DIST, "Unhog")
    shutil.rmtree(os.path.join(DIST, "Unhog"))

    # One-file build -> dist/Unhog.exe.
    pyinstaller("onefile")

    for name in sorted(os.listdir(DIST)):
        size = os.path.getsize(os.path.join(DIST, name)) / 1048576
        print(f"dist/{name}  ({size:.1f} MB)")
    return 0 if os.path.isfile(zip_path) and os.path.isfile(os.path.join(DIST, "Unhog.exe")) else 1


if __name__ == "__main__":
    sys.exit(main())
